### ISSUE TITLE
Upgrade to 2024.12.0 breaks custom cards

### ISSUE THREAD

**Issue by sofapi** [nathanmarlor/foxess_modbus_charge_period_card#21]
“Custom element does not exist. “

## Version of the custom_component

Up to date.

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

No custom charge cards appear to work after the update. Not sure if it’s linked to the way the custom cards are written, or the HAOS change?

## Debug log

```text

Add your logs here.

```

**Comment by sofapi** [comment]
Appears to be isolated to the iOS App only, noteworthy break but can be circumvented for no.

**Comment by canton7** [comment]
I suspect the app hasn't loaded or refreshed something. Force close and reopen / clear cache?
