### ISSUE TITLE
no inverter Present in dropdown menu

### ISSUE THREAD

**Issue by Vato9394** [nathanmarlor/foxess_modbus_charge_period_card#4]
I am stuck in the step "Select your inverter using the drop-down". no inverter is present. I installed both integrations and the sensors are populated. I restarted home assistant multiple times and even used different browsers and cleared the cache. I even tried to add the inverter in the YAML code of the card. no succes.
I have an AIO H3 8 connected to modbus usb.
Thanks for all the work you did regarding this!

```

**Comment by canton7** [comment]
Unfortunately the H3s don't allow setting charge periods over modbus. I'll make that clearer in the readme.

**Comment by canton7** [comment]
Fixed in 955036690f3b6274885570f98dc924e2ca88c290

**Comment by peterw10** [comment]
> Unfortunately the H3s don't allow setting charge periods over modbus.

Hello canton7, Foxess support wrote:
Einstellung des 3-teiligen Registers in Folge, Einstellung 44000 auf 7, Einstellung 44001 für Steuerzeit, Einheit S(Sekunde), Einstellung 44002 für Leistung, Einheit W(Watt).
Does this help?

**Comment by canton7** [comment]
If you can read from and write to those registers (using a tool such as [modpoll](https://www.modbusdriver.com/modpoll.html)), then I'll happily add support!

(Let's move the discussion over to https://github.com/nathanmarlor/foxess_modbus/discussions/465 -- this is to do with foxess_modbus, and not the card)

**Comment by canton7** [comment]
Actually, those look like Remote Control registers, not Charge Period registers.

We've just added support for Force Charge / Discharge work modes using Remote Control (see https://github.com/nathanmarlor/foxess_modbus/discussions/513), but that will not enable the use of this card, as this card is specifically for Charge Periods.

**Comment by Vato9394** [comment]
If I am understanding correctly, we can force charge/discharge the H3 through home assistant, but we cannot change the periods (for now, hopefully ;) )?
Can we add some card or edit this card without the "times" so we can enable/disable this manually?
Again, If I am understanding it correctly, we can use an automation to "enable" force charge on the H3? for example, when the price is low in Nordpool? and "disable" it when the price is getting high?

**Comment by canton7** [comment]
With the latest beta you can force charge / discharge, correct. I have seen nothing which suggests you can set charge periods for the H3 over modbus.

**Comment by Vato9394** [comment]
Thank you for your work, then we can use for example something like nordpool and force charge when the price is low (or negative) and automtically stop it when price gets over a certain threshold.
