### ISSUE TITLE
Card not available for setup in Dashboard

### ISSUE THREAD

**Issue by screenagerbe** [nathanmarlor/foxess_modbus_charge_period_card#6]
## Version of the custom_component

v1.0.0
HA 2023.8.1 (did not work on 2023.7.x)

## Configuration

Installed it through HACS as described in the README

## Describe the bug

The integration is installed via HACS without errors, but the card is just not available when trying to add a new card to any dashboard. I don't see the card, and I don't have a pop-up asking which inverter to add.

## Debug log

There is nothing 🤷‍♂️

**Comment by screenagerbe** [comment]
FYI,
I managed to configure it once on a dev device running HAOS, but now it says
![image](https://github.com/nathanmarlor/foxess_modbus_charge_period_card/assets/82099983/4bf6457f-0e64-4544-92de-98a2d229df97)

**Comment by canton7** [comment]
Does `/config/www/foxess-modbus-charge-period-card.js` exist?

Did you click the button to reload the UI when prompted by hacs?

**Comment by screenagerbe** [comment]
No not really.
Unless you mean `/config/www/community/foxess-modbus-charge-period-card/foxess-modbus-charge-period-card.js`

yes HA was reloaded, restarted and has even been updated too

**Comment by canton7** [comment]
If you navigate to HACS on the sidebar, do you see this message?

https://hacs.xyz/docs/faq/status_not_loaded/

**Comment by canton7** [comment]
(I managed to reproduce what I think is the issue you're seeing, and saw that message. Going to the 3 dots -> redownload fixed it)

**Comment by screenagerbe** [comment]
Everything looks OK in HACS, I don't see the "not loaded error", seen it before in other integrations, never in this though.
I have redownloaded the integration several times, to no avail

I have currently 3 HA systems running, and all three of them are having issues with the integration. As other users do not encounter these issues I'm starting to think it might have something to do with my FoxESS - Modbus setup

**Comment by canton7** [comment]
> I'm starting to think it might have something to do with my FoxESS - Modbus setup

No, the card is entirely independent of foxess-modbus, up to the point where it's up and running and tries to read your charge periods.

Are you using a custom ui-lovelace.yaml file by any chance?

**Comment by canton7** [comment]
Are you able to install (and use) any other lovelace cards through HACS?

Do you get any errors in the Console of your browser's developer tools when trying to add the charge period card to a dashboard?

**Comment by screenagerbe** [comment]
OK, that last tip gave it away.
It looks like you're sideloading js from an external domain?
![image](https://github.com/nathanmarlor/foxess_modbus_charge_period_card/assets/82099983/d0e5034e-ad4d-42d6-b7dd-e5638c514697)

Once I allow `unpkg.com` in NoScript it starts working.
Not sure if I like this kind of setup, though 🤨🤔

**Comment by screenagerbe** [comment]
Ok, that last tip gave it away
It looks like you're side loading js from an external domain?
![image](https://github.com/nathanmarlor/foxess_modbus_charge_period_card/assets/82099983/3fb7c222-df95-4a34-bd74-a22e476e006d)

Once I allowed unpkg.com in NoScript it started working.
Not sure if I like this setup though, because the side loaded js needs to be enabled to have a usable card at all, not only for configuration 🤔🤨

**Comment by canton7** [comment]
My options are basically:

1. Have a single vanilla JS file in the repo, which imports Lit from unpkg (which is that [the hass docs do](https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/#advanced-example))
2. Set up a whole JS packaging pipeline which bundles together Lit and this card, and commit the minified results to the repo (because HACS can't handle loading custom cards from release artifacts)

I wouldn't call it sideloading: loading a common library from a CDN is fairly standard practice (although admittedly it's less in fashion today than it was a few years ago)

**Comment by screenagerbe** [comment]
It still is a fairly common practice on websites, but I'm using NoScript for a reason 😅
It also means it'll stop working once your internet connection goes down (and you refresh your browser).

I can always clone this repo and add the whole JS packaging. Need to think about that one. 😏

**Comment by canton7** [comment]
Looks like HACS does support using release assets, so I'll get this change in.
