### ISSUE TITLE
Mismatched sensor naming between foxess_modbus integration and this lovelace card

### ISSUE THREAD

**Issue by shiraz-b** [nathanmarlor/foxess_modbus_charge_period_card#9]
## Version of the custom_component

[v1.0.1](https://github.com/nathanmarlor/foxess_modbus_charge_period_card/releases/tag/v1.0.1)

## Configuration

```yaml
Installed and successfully running https://github.com/nathanmarlor/foxess_modbus [v1.7.2](https://github.com/nathanmarlor/foxess_modbus/releases/tag/v1.7.2)
```

## Describe the bug

- Installed and successfully ran https://github.com/nathanmarlor/foxess_modbus [v1.7.2](https://github.com/nathanmarlor/foxess_modbus/releases/tag/v1.7.2)
- During the above installation chose a friendly name of "foxess 485 modbus"
- This resulted in sensors being created without the friendly name in the sensor name itself, but in the display name - not a problem in and of itself - everything works really well and I can see the data from the Invertor.
- Installed  this lovelace card
- Setup the card in a Dashboard
- The dashboard fails with the following errors:

![image](https://github.com/nathanmarlor/foxess_modbus_charge_period_card/assets/23420634/404366e6-b866-4961-b919-a8753283b263)

- I suspect this is a mismatch issue.  The lovelace card is expecting the sensor name to have the defined friendly name to be prepended to the sensor names, but the integration doesn't do this.

This is all great work and I'm happy to help in anyway I can with any beta versions/reviews etc - just let me know, thanks!

## Debug log

```text

N/A

```

**Comment by canton7** [comment]
Looks like the same as #8. You've misdiagnosed the issue slightly - the entity ids are supplied by the integration, but the entities don't have the id in HA that the integration specified. Either that, or some thing's broken. 

Thanks for the setup steps - I'll try and repro over the weekend.

**Comment by canton7** [comment]
Can you give v1.7.3b1 of the foxess_modbus integration a try please?

**Comment by shiraz-b** [comment]
Thanks @canton7 :  I'll give it a try today and confirm the outcome...

**Comment by shiraz-b** [comment]
Hi @canton7 : I can confirm after deleteing/reloading both the main integration to v1.7.3b1 and the lovelace integration (probably unecessarily) it all works.  Specifically:

- the EntityId's are now prefixed with the chosen name.
- the card is reading/writing to the integration correctly (confirmed by checking the foxesscloud battery settings after changing the lovelace UI)

Thank you so much!!

I'll stick with the beta until it's rolled into the main line tags...

Not sure of the process here - happy to close if you'd like?

**Comment by canton7** [comment]
Thanks! I'll get the beta released, then close this.

**Comment by canton7** [comment]
Released
